
# Copyright (c) 2026, Lei Meng

"""Walk a plan: funcs → blocks → stmts. Emit a LuaJIT module."""

from __future__ import annotations

from typing import Any

from ir2lua import __version__
from ir2lua.operands import (
    Operand,
    TranslateError,
    lua_ident,
    parse_local,
    parse_operand,
)
from ir2lua.stmts import parse_stmt


def _rego_func_name(func: dict[str, Any]) -> str:
    name = func.get("name")
    if isinstance(name, str) and name:
        return lua_ident(name)
    path = func.get("path") or []
    if path:
        return lua_ident("_".join(str(p) for p in path))
    raise TranslateError("function has no name or path")


def _rule_name(func: dict[str, Any]) -> str:
    path = func.get("path")
    if not isinstance(path, list) or not path:
        raise TranslateError(f"function {_rego_func_name(func)} has no path")
    last = path[-1]
    if not isinstance(last, str) or not last:
        raise TranslateError(f"function path has no rule name: {path!r}")
    return last


class _Translator:
    def __init__(self, plan: dict[str, Any], package: str):
        if not package:
            raise TranslateError("package name is required")
        self.plan = plan
        self.strings = _static_strings(plan)
        self.package = package
        self.lines: list[str] = []
        self.indent = 0
        self._declared: set[int] = set()
        self._known_def: set[int] = set()
        self._need_label = False
        self._returned = False
        self._fresh = 0
        self._planned: dict[str, str] = {}

    def add_line(self, line: str = "") -> None:
        if line == "":
            self.lines.append("")
        else:
            self.lines.append(("    " * self.indent) + line)

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def _declare_slot(self, idx: int) -> None:
        if idx in self._declared:
            return
        self._declared.add(idx)
        if idx == 0:
            self.add_line("local t0 = input or {}")
        elif idx == 1:
            self.add_line("local t1 = data or {}")
        else:
            self.add_line(f"local t{idx} = rt.UNDEF")

    def decl_local(self, raw: Any, what: str) -> int:
        idx = parse_local(raw, what)
        self._declare_slot(idx)
        return idx

    def resolve_operand(self, raw: Any, what: str) -> Operand:
        op = parse_operand(raw, self.strings, what)
        if op.local_index is not None:
            self._declare_slot(op.local_index)
        return op

    def jump_if(self, cond: str, label: str) -> None:
        self.add_line(f"if {cond} then goto {label} end")
        self._need_label = True

    def mark_return(self) -> None:
        self._returned = True

    def known_def(self, slot: int) -> bool:
        return slot in self._known_def

    def mark_def(self, slot: int) -> None:
        self._known_def.add(slot)

    def mark_undef(self, slot: int) -> None:
        self._known_def.discard(slot)

    def parse_nested(self, stmts: list[dict[str, Any]]):
        return [parse_stmt(self, n) for n in stmts]

    def fresh_label(self, prefix: str) -> str:
        self._fresh += 1
        return f"lbl_{prefix}_{self._fresh}"

    def planned_func_lua(self, name: str) -> str | None:
        return self._planned.get(name)

    def run(self) -> str:
        pkg = lua_ident(self.package)
        funcs = (self.plan.get("funcs") or {}).get("funcs")
        if not isinstance(funcs, list) or not funcs:
            raise TranslateError("plan has no funcs")

        self.add_line(f"-- generated by rego2lua v{__version__} from OPA plan IR")
        self.add_line()
        self.add_line('local rt = assert(loadfile("runtime/rego_rt.lua"))()')
        self.add_line(f"local {pkg} = {{}}")
        self.add_line()

        lua_names: list[str] = []
        self._planned = {}
        for fn in funcs:
            lua_name = _rego_func_name(fn)
            lua_names.append(lua_name)
            ir_name = fn.get("name")
            if isinstance(ir_name, str) and ir_name:
                self._planned[ir_name] = lua_name
        self.add_line("local " + ", ".join(lua_names))
        self.add_line()

        for fn in funcs:
            lua_name = _rego_func_name(fn)
            rule = lua_ident(_rule_name(fn))
            self._emit_func(fn)
            self.add_line(f"function {pkg}.{rule}(input, data)")
            self.indent += 1
            self.add_line(f"return {lua_name}(input, data)")
            self.indent -= 1
            self.add_line("end")
            self.add_line()

        self.add_line(f"return {pkg}")
        return self.text()

    def _emit_func(self, func: dict[str, Any]) -> None:
        name = _rego_func_name(func)
        blocks = func.get("blocks")
        if not isinstance(blocks, list):
            raise TranslateError(f"{name}: missing blocks")

        self._declared = set()
        n_params = 0
        self.add_line(f"{name} = function(input, data)")
        self.indent += 1
        self._declare_slot(0)
        self._declare_slot(1)
        for p in func.get("params") or []:
            self.decl_local(p, f"{name} param")
            n_params += 1
        if "return" in func:
            self.decl_local(func["return"], f"{name} return")
        parsed = [[parse_stmt(self, n) for n in (b.get("stmts") or [])] for b in blocks]
        self.add_line()

        self._returned = False
        for i, stmts in enumerate(parsed):
            skip = f"lbl_skip_b{i + 1}"
            self._need_label = False
            self._known_def = set(range(n_params))
            for node in stmts:
                node.emit(self, skip)
            if self._need_label:
                self.add_line()
                self.add_line(f"::{skip}::")
        if not self._returned:
            self.add_line("return rt.UNDEF")
        self.indent -= 1
        self.add_line("end")
        self.add_line()


def _static_strings(plan: dict[str, Any]) -> list[str]:
    raw = (plan.get("static") or {}).get("strings")
    if raw is None:
        return []
    if not isinstance(raw, list):
        raise TranslateError("static.strings must be an array")
    out: list[str] = []
    for i, item in enumerate(raw):
        if not isinstance(item, dict) or "value" not in item:
            raise TranslateError(f"static.strings[{i}] must be an object with value")
        val = item["value"]
        if not isinstance(val, str):
            raise TranslateError(f"static.strings[{i}].value must be a string")
        out.append(val)
    return out


def translate_plan(plan: dict[str, Any], package: str) -> str:
    return _Translator(plan, package).run()
