
# Copyright (c) 2026, Lei Meng <lynch.meng@hotmail.com>

"""Walk a plan: funcs → blocks → stmts. Emit a LuaJIT module."""

from __future__ import annotations

from typing import Any

from ir2lua import __version__
from ir2lua.operands import (
    Operand,
    TranslateError,
    lua_ident,
    parse_local,
    parse_operand,
    static_strings,
)
from ir2lua.stmts import parse_node

# Re-export for the CLI.
__all__ = ["TranslateError", "translate_plan"]


def _rego_func_name(func: dict[str, Any]) -> str:
    name = func.get("name")
    if isinstance(name, str) and name:
        return lua_ident(name.replace(".", "_"))
    path = func.get("path") or []
    if path:
        return lua_ident("_".join(str(p) for p in path))
    raise TranslateError("function has no name or path")


def _rule_name(func: dict[str, Any]) -> str:
    path = func.get("path")
    if not isinstance(path, list) or not path:
        raise TranslateError(f"function {_rego_func_name(func)} has no path")
    last = path[-1]
    if not isinstance(last, str) or not last:
        raise TranslateError(f"function path has no rule name: {path!r}")
    return last


class _Translator:
    def __init__(self, plan: dict[str, Any], package: str):
        if not package:
            raise TranslateError("package name is required")
        self.plan = plan
        self.strings = static_strings(plan)
        self.package = package
        self.lines: list[str] = []
        self.indent = 0
        self.slots: set[int] = set()
        self._params: set[int] = set()
        self._known_def: set[int] = set()
        self._need_label = False
        self._returned = False

    def add(self, line: str = "") -> None:
        if line == "":
            self.lines.append("")
        else:
            self.lines.append(("    " * self.indent) + line)

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def local(self, raw: Any, what: str) -> int:
        idx = parse_local(raw, what)
        self.slots.add(idx)
        return idx

    def operand(self, raw: Any, what: str) -> Operand:
        op = parse_operand(raw, self.strings, what)
        if op.local_index is not None:
            self.slots.add(op.local_index)
        return op

    def jump(self, cond: str, end: str) -> None:
        self.add(f"if {cond} then goto {end} end")
        self._need_label = True

    def mark_return(self) -> None:
        self._returned = True

    def known_def(self, slot: int) -> bool:
        return slot in self._known_def

    def mark_def(self, slot: int) -> None:
        self._known_def.add(slot)

    def mark_undef(self, slot: int) -> None:
        self._known_def.discard(slot)

    def run(self) -> str:
        pkg = lua_ident(self.package.replace(".", "_"))
        funcs = (self.plan.get("funcs") or {}).get("funcs")
        if not isinstance(funcs, list) or not funcs:
            raise TranslateError("plan has no funcs")

        self.add(f"-- generated by rego2lua {__version__} from OPA plan IR")
        self.add()
        self.add('local rt = assert(loadfile("runtime/rego_rt.lua"))()')
        self.add(f"local {pkg} = {{}}")
        self.add()

        for fn in funcs:
            rego_fn = _rego_func_name(fn)
            rule = lua_ident(_rule_name(fn))
            self._emit_func(fn)
            self.add(f"function {pkg}.{rule}(input, data)")
            self.indent += 1
            self.add(f"return {rego_fn}(input, data)")
            self.indent -= 1
            self.add("end")
            self.add()

        self.add(f"return {pkg}")
        return self.text()

    def _emit_func(self, func: dict[str, Any]) -> None:
        name = _rego_func_name(func)
        blocks = func.get("blocks")
        if not isinstance(blocks, list):
            raise TranslateError(f"{name}: missing blocks")

        self.slots = set()
        self._params = set()
        for p in func.get("params") or []:
            self._params.add(self.local(p, f"{name} param"))
        if "return" in func:
            self.local(func["return"], f"{name} return")
        parsed = [[parse_node(self, n) for n in (b.get("stmts") or [])] for b in blocks]

        self.add(f"local function {name}(input, data)")
        self.indent += 1
        max_slot = max(self.slots) if self.slots else 1
        if max_slot < 1:
            max_slot = 1
        for i in range(0, max_slot + 1):
            if i == 0:
                self.add("local t0 = input or {}")
            elif i == 1:
                self.add("local t1 = data or {}")
            else:
                self.add(f"local t{i} = rt.UNDEF")

        self._returned = False
        for i, stmts in enumerate(parsed):
            end = f"block_{i}_end"
            self._need_label = False
            self._known_def = set(self._params)
            for node in stmts:
                node.emit(self, end)
            if self._need_label:
                self.add(f"::{end}::")
        if not self._returned:
            self.add("return rt.UNDEF")
        self.indent -= 1
        self.add("end")
        self.add()


def translate_plan(plan: dict[str, Any], package: str) -> str:
    return _Translator(plan, package).run()
