
# Copyright (c) 2026, Lei Meng

"""Codegen context and lowered-statement protocol."""

from __future__ import annotations

from typing import Any, Protocol

from ir2lua.operands import Operand


class Emit(Protocol):
    def add(self, line: str = "") -> None: ...
    def jump(self, cond: str, end: str) -> None: ...
    def local(self, raw: Any, what: str) -> int: ...
    def operand(self, raw: Any, what: str) -> Operand: ...
    def mark_return(self) -> None: ...
    def known_def(self, slot: int) -> bool: ...
    def mark_def(self, slot: int) -> None: ...
    def mark_undef(self, slot: int) -> None: ...


class Lowered(Protocol):
    def emit(self, cx: Emit, end: str) -> None: ...
